added Jensen plot
morganjwilliams/pyrolite pull request #74
Opened 2022-05-03 00:19 UTC by AngRodrigues

Added Jensen ternary plot for the classification of sub-alkaline volcanic rocks.

## Description
Followed the already existing .json template to generate the a new template for Jensen plot with the classification of sub-alkaline rocks.  

## Related Issue
No issue associated. 

## Motivation and Context
Jensen plot was not previously available in pyrolite, and I needed to use a Jensen plot in my code. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ x ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-05-04 04:18 UTC, morganjwilliams requested changes
Hey @AngRodrigues, thanks for the PR, and nice work on your first! This runs locally and I've added a few minor things to address in comments here. 

It might be good to work up an example which can be added to the docs pages (and also used in a test), but we can do that subsequently as desired. I've added a specification for a quick synthetic dataset which isn't exactly 'natural' but otherwise demonstrates the space below (note that if axes names are changed, they should be changed here too..).

```python
from pyrolite.util.synthetic import normal_frame, random_cov_matrix

df = normal_frame(
        columns=["Ti + Fe(tot) cat %", "Al cat %", "Mg cat %"],
        mean=[0.07, 0.15, 0.12],
        cov=random_cov_matrix(2, sigmas=[0.5, 0.7]),
        size=100,
      )
```

2022-06-26 21:28 UTC, AngRodrigues commented on .vscode/settings.json
> +{
Sure, it has been removed from PR

2022-06-26 21:30 UTC, AngRodrigues commented on pyrolite/data/models/JensenPlot/config.json
> +{"name": "JensenPlot", "axes": {"t": "Ti + Fe(tot) cat %", "l": "Al cat %", "r": "Mg cat %"}, "transform": "ternary",
changed to mol%

2022-06-26 21:36 UTC, AngRodrigues commented on pyrolite/data/models/JensenPlot/config.json
> +    {"High Ti-Fe Other": {"name": "High Ti Fe Other", "poly": [[100, 0, 0], [85, 0, 15], [70, 15, 15], [85, 15, 0]]},
Yes, I was a bit confused on which labels are used in the figure; it's nice that both can be used. Updated as per suggested.

2022-06-26 21:39 UTC, AngRodrigues commented on pyrolite/data/models/USDASoilTexture/config.json
> -{"name": "USDA-Soil-Texture", "axes": {"t": "Clay", "l": "Sand", "r": "Silt"}, "transform": "ternary", "fields": {"sand": {"name": "Sand", "poly": [[0, 100, 0], [10, 90, 0], [0, 85, 15]]}, "loamy-san
Agreed; reset to the previous version.

2022-06-26 21:40 UTC, AngRodrigues commented on pyrolite/plot/templates/JensenPlot.py
> +    # .. [#ref_1] Jensen, L. S. (1976) A new cation plot for classifying sub-alkaline volcanic rocks.
Done.

2022-06-26 21:41 UTC, AngRodrigues commented on pyrolite/plot/templates/JensenPlot.py
> +    # """
Nice catch! Done

2022-06-26 23:51 UTC, AngRodrigues commented on pyrolite/util/classification.py
> +    References
Added notes at the end. Not too familiar with more current approaches for this, but added some extra information.

2022-07-06 06:38 UTC, merged