Pettijohn and Herron classifications plots for sandstones
morganjwilliams/pyrolite pull request #82
Opened 2023-05-23 12:50 UTC by ondrolexa

Added plots for geochemical classification of sandstones

## Description
These two scatter plots are commonly used to classify sandstones based on geochemistry.

## Types of changes
- [`x`] New feature (non-breaking change which adds functionality)

## Checklist:
- [`x`] My code follows the code style of this project.
- [`x`] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-05-26 01:23 UTC, morganjwilliams commented
Hey @ondrolexa! Thanks for the PR, I'll have a look through and add any comments shortly.

2023-05-26 03:36 UTC, morganjwilliams requested changes
Hey again @ondrolexa, a few things here which might be worth quickly updating but otherwise looks good! If you're interested you could consider adding a diagram example to the docs page [here](https://github.com/morganjwilliams/pyrolite/blob/develop/docs/source/gallery/examples/plotting/templates.py), but I have a few other things to add there later so happy to update this myself.

2023-05-26 03:36 UTC, morganjwilliams commented on pyrolite/data/models/sandstones/config_herron.json
> +{"name": "Herron", "axes":{"x":"log(SiO2/Al2O3)","y":"log(Fe2O3/K2O)"},
To avoid potential ambiguity here, I'd suggest using either e.g. `ln(SiO2/Al2O3)` or `log10(SiO2/Al2O3)` as is appropriate.

2023-05-26 03:36 UTC, morganjwilliams commented on pyrolite/data/models/sandstones/config_pettijohn.json
> +{"name": "Pettijohn", "axes":{"x":"log(SiO2/Al2O3)","y":"log(Na2O/K2O)"},
Note as above re: `ln`/`log10`

2023-05-26 03:36 UTC, morganjwilliams commented on pyrolite/plot/templates/__init__.py
> +    "sandstones",
Rather than `"sandstones"` here, I'd suggest using the diagram names `"Pettijohn", "Herron"`.

2023-05-26 03:36 UTC, morganjwilliams commented on pyrolite/plot/templates/sandstones.py
> +    tas = PJclassifier()
The variable name here is a bit of a hangover from the TAS class, could consider renaming to `pjc` or similar?

2023-05-26 03:36 UTC, morganjwilliams commented on pyrolite/plot/templates/sandstones.py
> +    tas = Herronclassifier()
Note as above re: inherited TAS variable name.

2023-05-26 03:36 UTC, morganjwilliams commented on pyrolite/plot/templates/sandstones.py
> +Pettijohn.__doc__ = Pettijohn.__doc__.format(
Thanks for adding the references!

2023-05-26 03:38 UTC, morganjwilliams commented
Another note, please feel free to add yourself to [the contributors list](https://github.com/morganjwilliams/pyrolite/blob/develop/docs/source/dev/contributors.rst) as part of the PR!

2023-05-26 05:09 UTC, ondrolexa commented
@morganjwilliams I can update examples in docs next week, when back from family trip.

2023-05-29 08:15 UTC, ondrolexa commented
@morganjwilliams I just modified the PR according to your comments. I left it for you to add examples, as it is not fully clear to me how images etc are generated... Simply you can add code under templates as

      from pyrolite.plot.templates import Pettijohn, Herron
      
      fig, ax = plt.subplots(1, 2, figsize=(10, 4))
      share_axes(ax, which="x")  # these diagrams have the same x axis
      
      Pettijohn(ax=ax[0], add_labels=True)
      Herron(ax=ax[1], add_labels=True)
      
      plt.tight_layout()  # nicer spacing for axis labels

2023-05-30 01:43 UTC, morganjwilliams approved these changes

2023-05-30 01:48 UTC, morganjwilliams commented
Thanks @ondrolexa, looks good! I'll add the snippet to the docs and link the page here.

On the docs, for future reference (of yourself, or anyone else trawling through), these are built with `sphinx-gallery`. Essentially I write cell-delimited `.py` files, which during the docs-buillding on `ReadtheDocs` are compiled to Jupyter notebooks, which are then run-through and turned into HTML with inline outputs (i.e. the figures). A little convoluted, but keeps the inputs small and consistent. For this example, the page to edit would be [./docs/source/gallery/examples/plotting/templates.py](https://github.com/morganjwilliams/pyrolite/blob/develop/docs/source/gallery/examples/plotting/templates.py).

2023-05-30 01:49 UTC, merged

2023-05-30 03:05 UTC, morganjwilliams commented
All going well, updates to the docs example should be [here](https://pyrolite.readthedocs.io/en/develop/examples/plotting/templates.html) shortly.

2023-05-30 05:23 UTC, ondrolexa commented
One typo in docs.... Just before code block there is pearceThNbYb() instead Pettijohn().

2023-05-30 05:35 UTC, morganjwilliams commented
Thanks for the pickup! I've made a change which should come through shortly.